name: Deplo To COS

on:
  # 允许手动push触发
  push:
    branches:
      - master
  # 允许外部仓库事件触发
  repository_dispatch:
    types:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENABLE_YUQUE: ${{ secrets.ENABLE_YUQUE }}

    steps:
      - name: 检查分支
        uses: actions/checkout@master

      - name: 安装node环境
        uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: 安装pnpm
        run: |
          export TZ='Asia/Shanghai'
          npm install pnpm@7.9.5 -g

      - name: 缓存依赖
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/pnpm-lock.yaml')}}

      - name: 安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          export TZ='Asia/Shanghai'
          pnpm install --prod

      - name: 安装COS相关依赖
        run: |
          sudo pip install coscmd
          sudo pip install tccli==3.0.575.1

      - name: 配置COS
        env:
          COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
          COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
          COS_BUCKET: ${{ secrets.COS_BUCKET }}
          COS_REGION: ${{ secrets.COS_REGION }}
        run: |
          coscmd config -a $COS_SECRET_ID -s $COS_SECRET_KEY -b $COS_BUCKET -r $COS_REGION
          tccli configure set secretId $COS_SECRET_ID
          tccli configure set secretKey $COS_SECRET_KEY
          tccli configure set region $COS_REGION

      - name: 清除语雀缓存(拉取全部文章)
        env:
          CLEAN_CACHE: ${{ secrets.CLEAN_CACHE }}
        if: ${{ env.CLEAN_CACHE == 'true' }}
        run: |
          pnpm clean:yuque
          pnpm clean:notion

      - name: 拉取语雀的文章
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          YUQUE_LOGIN: ${{ secrets.YUQUE_LOGIN }}
          YUQUE_REPO: ${{ secrets.YUQUE_REPO }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
          COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
          COS_IMAGE_BUCKET: ${{ secrets.COS_IMAGE_BUCKET }}
          COS_IMAGE_REGION: ${{ secrets.COS_IMAGE_REGION }}
        run: |
          pnpm sync:yuque
          pnpm sync:notion

      - name: 配置Git用户名邮箱
        run: |
          git config --global user.name "1874"
          git config --global user.email "1225751694@qq.com"

      - name: 提交yuque拉取的文章到GitHub仓库
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt
          git add .
          git commit -m "Refresh yuque json" -a

      - name: 推送文章到仓库
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 生成静态文件
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
        run: |
          pnpm docs:build

      - name: 上传文章到cos并刷新CDN
        run: |
          coscmd upload -rfs --delete ./docs/.vitepress/dist/ /
          tccli cdn PurgePathCache --cli-unfold-argument --Paths https://elog.1874.cool/ --FlushType flush
          # from https://github.com/peaceiris/actions-gh-pages
